[tox]
toxworkdir = cache/.tox
envlist =
    py{310,311,312,313,314}
	linter

[testenv]
deps =
    -r requirements/test.txt
commands =
    pip install -e .
    pytest .

[testenv:linter]
deps =
    -r requirements/test.txt
commands =
    flake8 src/attix/.
    black --check src/attix/.
    mypy src/attix/.
